language: ruby

sudo: false

before_install:
  - gem update --system -q
  - gem update bundler -q

install: ruby -S bundle install --without release development

rvm:
  - 1.9.3
  - 2.4.2
  - 2.5
  - ruby-head
  - jruby-9.1.16.0

branches:
  only:
    - master
    - 2.5-stable

matrix:
  allow_failures:
    - rvm: ruby-head

env:
  global:
    - CI="travis"
    - JRUBY_OPTS="--server -J-Xms512m -J-Xmx1024m"

script:
  - |
    for MONGODB_VERSION in 2.6.12 3.0.15 3.2.20 3.4.14 3.6.5; do
      echo "CI test on MONGODB_VERSION: ${MONGODB_VERSION}"
      MONGODB_VERSION="${MONGODB_VERSION}" bundle exec rake spec:ci
    done

notifications:
  email: false
