language: ruby

sudo: true

rvm:
  #- 1.9.3
  #- 2.4.2
  - 2.5
  #- ruby-head
  #- jruby-19mode
  #- jruby-9.1.15.0

before_install:
  - |
    if [ "${EXTERNAL_DISABLE}" != "" ]; then
      apt-get remove resolvconf
    fi
  - gem update --system
  - gem update bundler

install: ruby -S bundle install --without release development

env:
  global:
    - CI="travis"
    - EXTERNAL_DISABLED=1
    - JRUBY_OPTS="--server -J-Xms512m -J-Xmx1024m"
  matrix:
    #- MONGODB=2.6.12
    #- MONGODB=3.0.12
    #- MONGODB=3.2.11
    #- MONGODB=3.4.1
    - MONGODB=3.6.2

before_script:
  - wget http://fastdl.mongodb.org/linux/mongodb-linux-x86_64-${MONGODB}.tgz -O /tmp/mongodb.tgz
  - tar -xvf /tmp/mongodb.tgz
  - mkdir /tmp/data
  - ${PWD}/mongodb-linux-x86_64-${MONGODB}/bin/mongod --dbpath /tmp/data --bind_ip 127.0.0.1 --auth &> /dev/null &

script: bundle exec rake spec:ci

notifications:
  email: false
  flowdock: 1da4416b8ff98d1880986472428b1b1b

#branches:
#  only:
#    - master
#    - 1.x-stable

matrix:
  allow_failures:
    - rvm: ruby-head
