dist: xenial
language: ruby
matrix:
  include:
    - rvm: "2.6.5"
      env:
        - MONGODB_VERSION=3.6.15
    - rvm: "2.7.0"
      env:
        - MONGODB_VERSION=3.6.15
      before_install:
        - gem uninstall bundler -x
    - rvm: ruby-head
      env:
        - MONGODB_VERSION=3.6.15
      before_install:
        - gem uninstall bundler -x
  allow_failures:
    - rvm: ruby-head
env:
  global:
    - CI="travis"
    - EXTERNAL_DISABLED=1
before_install:
  - gem update --system -q
  - gem update bundler -q
install: bundle install --without release development
script: bundle exec rake spec:ci_standalone
